### ISSUE TITLE
Log Failed Login Attempts

### ISSUE THREAD

**Issue by thomaskonrad** [ChristophWurst/twofactor_totp#32]
Hi,

it would be great if you could log failed two-factor authentication attempts to the standard ownCloud log file (```data/owncloud.log```). This way, it would be possible to lock IP addresses where too many failed attempts come from, and generally, one would have the possibility to detect that somebody stole the main password and is attempting to brute-force the TOTP.

Thank you
Thomas

**Comment by ChristophWurst** [comment]
Hi,
that would be a nice enhancement. Failed password logins are logged too. Since logging failed second factor auth attempts makes also sense for any other factor, I think that should be added to server/core instead of this specific app. Otherwise all apps have to add their own logging and it's then harder to filter different log formats in ``nextcloud.log``/`owncloud.log`.

**Comment by ChristophWurst** [comment]
Feel free to open an issue in https://github.com/nextcloud/server. If you'd like to implement that I can also point you to the classes/files where you'd have to add it :wink:
