### ISSUE TITLE
App Passwords Dissappear

### ISSUE THREAD

**Issue by rogersia** [ChristophWurst/twofactor_totp#70]
If you enable TOTP second-factor auth, you need to use the App Passwords to connect the mobile clients to your account.

When you create the App password, it shows the username and password, you can then click done to hide those and it is just the name in the App passwords section.

When you re-load the user screen, the list of app passwords is then blank.  You can add more and the same happens.

The app passwords still work.

**Comment by ChristophWurst** [comment]
Which version of Nextcloud do you use?

**Comment by rogersia** [comment]
I have OwnCloud 9.1.1

I can't find a copy of 9.2, latest I could find was 9.1.1 RC3

**Comment by ChristophWurst** [comment]
I see. This is an issue of the ownCloud core then. Since there have been other users with other problems that they exclusively experienced with ownCloud, I can recommend to migrate to Nextcloud. For other users this has solved their problems. This app is also not maintained for OC anymore, newer versions will only be available for Nextcloud.
Let me know if you need help with the migration.
